security:
  oauth2:
    client:
      client-id: client
      client-secret: oauth2-client
      registered-redirect-uri: http://localhost/api/spring-boot-security-oauth2-auth
    resource:
      id: resource-server
      # user-info-uri和token-info-uri二选择即可
      # 如果配置了user-info-uri，该资源服务器使用userInfoTokenServices远程调用认证中心接口，
      # 通过认证中心的OAuth2AuthenticationProcessingFilter完成验证工作，一般设置user-info-uri即可
      #user-info-uri: http://127.0.0.1:8001/user
      prefer-token-info: false
      # 该资源服务器使用RemoteTokenServices远程调用认证中心接口，注意一点就是如果使用token-info-uri那么就必须设置上clientId和clientSecret，
      # 通过CheckTokenEndpoint完成验证工作
      token-info-uri: http://localhost/api/spring-cloud-oauth2-auth/oauth/check_token
      #registered-redirect-uri: http://localhost
#http://localhost/api/spring-cloud-oauth2-auth/oauth/authorize?response_type=code&client_id=client&redirect_uri=http://localhost/api/spring-cloud-oauth2-auth&scope=all&state=hello
#http://localhost/oauth/authorize?response_type=code&client_id=client&redirect_uri=http://localhost&scope=all&state=hello