spring:
  application.name: @project.name@
  profiles.include: eureka-client, loadbalancer
server:
  port: @project.port@
  address: @project.address@
  servlet.context-path: /api/@project.artifactId@
  compression.enabled: true
  tomcat:
    uri-encoding: UTF-8
    basedir: D:/Logs/tomcat/tmp
