knife4j:
  #开启增强功能
  enable: true
  #swagger会解析的包路径
  basePackage: @project.groupId@
  #分组名称
  groupName: @project.parent.groupId@
  #标题
  title: ${spring.application.name}
  #描述
  description: @project.description@
  #版本
  version: @project.version@
  #许可证
  license: ...
  #许可证URL
  licenseUrl: ...
  #服务条款URL
  termsOfServiceUrl: ...
  #host信息
  host: 127.0.0.1
  #联系人信息
  contact:
    #联系人
    name: cmmplb
    #联系人url
    url: www.cmmplb.com
    #联系人email
    email: cmmplb@.com