apiVersion: v1
kind: Service
metadata:
  name: spring-cloud-kubernetes-loadbalancer-provider
  namespace: cmmplb
  labels:
    app: spring-cloud-kubernetes-loadbalancer-provider
spec:
  type: NodePort
  ports:
    - port: 18082
      nodePort: 30082
      protocol: TCP
      name: http
  selector:
    app: spring-cloud-kubernetes-loadbalancer-provider

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-cloud-kubernetes-loadbalancer-provider
  namespace: cmmplb
  labels:
    app: spring-cloud-kubernetes-loadbalancer-provider
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-cloud-kubernetes-loadbalancer-provider
  template:
    metadata:
      labels:
        app: spring-cloud-kubernetes-loadbalancer-provider
    spec:
      # 拉取私有镜像配置Secret，没有就创建kubectl create secret docker-registry aliyun-registry --docker-server=registry.cn-hangzhou.aliyuncs.com --docker-username=xxx --docker-password=xxx -n cmmplb
      # kubectl get secret aliyun-registry -o yaml -n cmmplb
      imagePullSecrets:
        - name: aliyun-registry
      containers:
        - name: spring-cloud-kubernetes-loadbalancer-provider
          image: "registry.cn-hangzhou.aliyuncs.com/cmmplb/spring-cloud-kubernetes-loadbalancer-provider:1.0.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 18082
              protocol: TCP

