# 负载均衡器缓存
spring:
  cloud:
    loadbalancer:
      cache:
        # 关闭缓存配置，警告
        # Spring Cloud LoadBalancer is currently working with the default cache. You can switch to using Caffeine cache,
        # by adding it and org.springframework.cache.caffeine.CaffeineCacheManager to the classpath
        enabled: false
        caffeine:
          spec: initialCapacity=500,expireAfterWrite=5s