spring:
  application.name: spring-cloud-eureka-provider
  profiles.include: eureka-client, loadbalancer, logging, management
server:
  port: 80
  address: @project.address@
  #servlet.context-path: /api/@project.artifactId@
  compression.enabled: true
  tomcat:
    uri-encoding: UTF-8
    basedir: D:/Logs/tomcat/tmp
